### ISSUE TITLE
Crash wile cycling when the status bar is unset

### ISSUE THREAD

**Issue by lenormf** [jwlodek/py_cui#116]
**Describe the bug**
When the status bar is unset, cycling through widgets makes the program crash.

**To Reproduce**
1. Set `status_bar` to `None` in the `PyCUI` instance
2. Cycle through widgets

Error:

```
Traceback (most recent call last):
  File "/home/fle/misc/4dE/./4dE.py", line 69, in <module>
    sys.exit(main(sys.argv))
  File "/home/fle/misc/4dE/./4dE.py", line 63, in main
    root.start()
  File "/home/fle/misc/4dE/.env/lib/python3.9/site-packages/py_cui/__init__.py", line 317, in start
    curses.wrapper(self._draw)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/fle/misc/4dE/.env/lib/python3.9/site-packages/py_cui/__init__.py", line 1562, in _draw
    self._cycle_widgets()
  File "/home/fle/misc/4dE/.env/lib/python3.9/site-packages/py_cui/__init__.py", line 1080, in _cycle_widgets
    self.move_focus(self.get_widgets()[next_widget_id], auto_press_buttons=False)
  File "/home/fle/misc/4dE/.env/lib/python3.9/site-packages/py_cui/__init__.py", line 1047, in move_focus
    self.status_bar.set_text(widget.get_help_text())
AttributeError: 'NoneType' object has no attribute 'set_text'
```

**Comment by voryzen** [comment]
@lenormf
See here: https://github.com/jwlodek/py_cui/issues/161#issuecomment-986009014
