### ISSUE TITLE
Trouble installing via pip on Windows

### ISSUE THREAD

**Issue by livvy94** [jwlodek/py_cui#182]
**Describe the bug**
pip cannot successfully acquire py-cui

**To Reproduce**
run `pip install py-cui` in Powershell via the Windows Terminal

**Screenshots**
```
Collecting py-cui
  Using cached py_cui-0.1.6.tar.gz (63 kB)
  Preparing metadata (setup.py) ... done
  Using cached py_cui-0.1.5.tar.gz (62 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\vince\AppData\Local\Temp\pip-install-d64ccod3\py-cui_31f73aff77c54f45baaaa1c68fc51e51\setup.py", line 8, in <module>
          with open('requirements.txt', 'r') as req_fp:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Environment*:*
 - OS: Windows 11
 - Terminal: PowerShell in Windows Terminal
 - Version: 1.12.10983.0
   - pip version is `pip 22.3.1 from C:\msys64\mingw64\lib\python3.10\site-packages\pip (python 3.10)`
   - python version is 3.10.5

**Comment by jwlodek** [comment]
I can't reproduce with `py_cui` 0.1.6:

```
PS C:\Users\jwlodek> pip install py_cui
Collecting py_cui
  Using cached py_cui-0.1.6-py3-none-any.whl
Requirement already satisfied: windows-curses in c:\users\jwlodek\appdata\local\programs\python\python38\lib\site-packages (from py_cui) (2.2.0)
Installing collected packages: py-cui
Successfully installed py-cui-0.1.6
```

The 0.1.5 release has this problem - it was an oversight  when I uploaded to PyPi, which is why 0.1.6 was released. It seems in your case pip is trying to install the cached 0.1.5 version. Could you try purging `py_cui` from the cache and installing fresh?

**Comment by livvy94** [comment]
I just ran `pip cache purge` and tried installing again, and it says this:
```
Collecting py-cui
  Downloading py_cui-0.1.6.tar.gz (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 1.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading py_cui-0.1.5.tar.gz (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.9/62.9 kB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\vince\AppData\Local\Temp\pip-install-auwf9i3x\py-cui_d20a88d9ebfe40fdacf7a2e0519f99da\setup.py", line 8, in <module>
          with open('requirements.txt', 'r') as req_fp:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
