### ISSUE TITLE
Local pip installation seems to be broken on windows

### ISSUE THREAD

**Issue by jwlodek** [jwlodek/py_cui#96]
**Describe the bug**
Locally installing with pip doesn't install the required `windows-curses` helper library.

**To Reproduce**
1. `git clone https://github.com/jwlodek/py_cui`
2. `cd py_cui`
3. `pip install .`

**Expected behavior**
`windows-curses` should be installed first, then the py_cui library.

**Screenshots**
```
(venv) E:\ProgrammingWorkspace\py_cui>pip install .
Processing e:\programmingworkspace\py_cui
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jw~1\AppData\Local\Temp\pip-req-build-9wk6nbae\setup.py", line 3, in <module>
        import py_cui
      File "C:\Users\jw~1\AppData\Local\Temp\pip-req-build-9wk6nbae\py_cui\__init__.py", line 24, in <module>
        import curses
      File "C:\Program Files\Python37\lib\curses\__init__.py", line 13, in <module>
        from _curses import *
    ModuleNotFoundError: No module named '_curses'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\jw~1\AppData\Local\Temp\pip-req-build-9wk6nbae\
You are using pip version 10.0.1, however version 21.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Environment*:*
 - OS: Windows 10
 - Terminal: cmd
 - Version: v0.1.3

**Comment by jwlodek** [comment]
Pretty sure this is caused by f8d6e318f0af75c84d9a43b2bc92607955f49992

Importing py_cui to determine version is done before windows-curses is installed, causing an import error.

**Comment by jwlodek** [comment]
Reverted change with b7473fe3e83bea9d1df9c835db419fd6eea93bf2 and fixed issue.
